In [57]:
## Setup Overlay en MMAPs
from pynq import Overlay
from pynq import MMIO

ov = Overlay('aivo.bit')
base_address = 0x43C00000
ctrl_size = 2**10
ctrl_mmap = MMIO(base_address, ctrl_size)
imem_size = ctrl_mmap.read(0x318)
dmem_size = ctrl_mmap.read(0x314)
pmem_size = ctrl_mmap.read(0x31C)
    
region_size = max([ctrl_size, imem_size, dmem_size, pmem_size])
imem_mmap = MMIO(base_address + region_size, imem_size)
dmem_mmap = MMIO(base_address + region_size*2, dmem_size)
pmem_mmap = MMIO(base_address + region_size*3, pmem_size)
print("imem_size: {}".format(imem_size))
print("dmem_size: {}".format(dmem_size))
print("pmem_size: {}".format(pmem_size))

imem_size: 131072
dmem_size: 8192
pmem_size: 1


In [58]:
## Write IMEM/DMEM/PMEM
i = 0
with open("main.img", mode="r") as file:
    for line in file:
        line = line.strip().rjust(128, '0') # 128
        for j in [3,2,1,0]: # 3
            i_word = int(line[(32*j):(32*j+32)], 2)
            imem_mmap.write(i, i_word)
            i += 4
i = 0
with open("main_data.img", mode="r") as file:
    for line in file:
        line = line.strip().rjust(32, '0')
        i_word = int(line, 2)
#         if i_word != 0:
#             print("{} at {}".format(i_word, i))
        dmem_mmap.write(i, i_word)
        i += 4
# i = 0
# with open("main_parameters.img", mode="r") as file:
#     for line in file:
#         line = line.strip().rjust(32, '0')
#         i_word = int(line, 2)
#         #if i_word != 0:
#         #    print("{} at {}".format(i_word, i))
#         pmem_mmap.write(i, i_word)
#         i += 4

In [59]:
# Setup CMA data
from pynq import Xlnk
import numpy as np 
xlnk = Xlnk()

offset = 256 # MMAP address

size = (48, 32)
FM = 64
aFM = int(FM/32)
# Real data
l0_input = xlnk.cma_array(shape=(size[0]*size[1]), dtype=np.int16)
l0_input[:] = np.fromfile("data/input/{}x{}.bin".format(size[0], size[1]), dtype=np.int16)
dmem_mmap.write(offset, l0_input.physical_address)

l0_weights = xlnk.cma_array(shape=(FM*3*3), dtype=np.int16)
l0_weights[:] = np.fromfile("data/weights/conv0.bin", dtype=np.int16)
dmem_mmap.write(offset+4, l0_weights.physical_address)

# Outputs
l0_output = xlnk.cma_array(shape=(FM*size[0]*size[1]), dtype=np.int32)
# l0_output[:] = np.fromfile("data/ref/{}x{}/conv0.bin".format(size[0], size[1]), dtype=np.int32)
dmem_mmap.write(offset+8, l0_output.physical_address)

l0_act = xlnk.cma_array(shape=(aFM*size[0]*size[1]), dtype=np.uint32)
l0_act[:] = np.fromfile("data/ref/{}x{}/act0.bin".format(size[0], size[1]), dtype=np.uint32)
dmem_mmap.write(offset+12, l0_act.physical_address)

offset += 16
B_w = []
B_out = []
B_act = []
B_thres = []
for i in range(1, 15):
    w = xlnk.cma_array(shape=(FM*3*3*aFM), dtype=np.uint32)
    w[:] = np.fromfile("data/weights/conv{}.bin".format(i), dtype=np.uint32)
    B_w.append(w)
    dmem_mmap.write(offset, w.physical_address)

    out = xlnk.cma_array(shape=(FM*size[0]*size[1]), dtype=np.uint16)
    B_out.append(out)
    dmem_mmap.write(offset+4, out.physical_address)

    act = xlnk.cma_array(shape=(aFM*size[0]*size[1]), dtype=np.uint32)
    B_act.append(act)
    dmem_mmap.write(offset+12, act.physical_address)

    thres = xlnk.cma_array(shape=(FM), dtype=np.uint16)
    thres[:] = np.fromfile("data/thresholds/act{}.bin".format(i), dtype=np.uint16)
    B_thres.append(thres)
    dmem_mmap.write(offset+8, thres.physical_address)
    
    offset += 16

l15_weights = xlnk.cma_array(shape=(FM*3*3*aFM), dtype=np.uint32)
l15_weights[:] = np.fromfile("data/weights/conv{}.bin".format(15), dtype=np.uint32)
dmem_mmap.write(offset, l15_weights.physical_address)

l15_out = xlnk.cma_array(shape=(FM*size[0]*size[1]), dtype=np.uint16)
# l15_out[:] = np.fromfile("data/output/conv15.bin", dtype=np.uint16) ###
dmem_mmap.write(offset+4, l15_out.physical_address)
offset += 8

# ReLU
relu_thres_a = xlnk.cma_array(shape=(FM), dtype=np.int16)
relu_thres_a[:] = np.fromfile("data/thresholds/act15_a.bin", dtype=np.int16)
dmem_mmap.write(offset, relu_thres_a.physical_address)

relu_thres_b = xlnk.cma_array(shape=(FM), dtype=np.int32)
relu_thres_b[:] = np.fromfile("data/thresholds/act15_b.bin", dtype=np.int16).astype(np.int32)
dmem_mmap.write(offset + 4, relu_thres_b.physical_address)

relu_out = xlnk.cma_array(shape=(FM*size[0]*size[1]), dtype=np.int16)
# relu_out[:] = np.fromfile("data/output/act15.bin", dtype=np.int16) ###
dmem_mmap.write(offset + 8, relu_out.physical_address)
offset += 12

# Conv 16
l16_weights = xlnk.cma_array(shape=(FM*3*3), dtype=np.int16)
l16_weights[:] = np.fromfile("data/weights/conv16.bin", dtype=np.int16)
dmem_mmap.write(offset, l16_weights.physical_address)

# Outputs
l16_output = xlnk.cma_array(shape=(size[0]*size[1]), dtype=np.int32)
dmem_mmap.write(offset + 4, l16_output.physical_address)

print(offset+4)

520


In [60]:
import time
# Run TTA
ctrl_mmap.write(0x200, 0x2)
time.sleep(5)
ctrl_mmap.write(0x200, 0x1)

In [61]:
# Printout DMEM
for i in range(0, dmem_size, 4):
    val = dmem_mmap.read(i)
    if val != 0:
        print("b{}, 0x{}, {} at {}, phys: {}".format(bin(val)[2:].zfill(32), hex(val)[2:].zfill(8), val, i, hex(i+dmem_mmap.base_addr)))

b00000000000000000000000010000000, 0x00000080, 128 at 128, phys: 0x43c40080
b00000000000000000000000000110000, 0x00000030, 48 at 136, phys: 0x43c40088
b00000000000000000000000000100000, 0x00000020, 32 at 140, phys: 0x43c4008c
b00000000000000000000000000000001, 0x00000001, 1 at 144, phys: 0x43c40090
b00000000000000000000000000000011, 0x00000003, 3 at 148, phys: 0x43c40094
b00000000000000000000000000000011, 0x00000003, 3 at 152, phys: 0x43c40098
b00000000000000000000000000000001, 0x00000001, 1 at 156, phys: 0x43c4009c
b00000000000000000000000000000001, 0x00000001, 1 at 160, phys: 0x43c400a0
b00011000000010010111000000000000, 0x18097000, 403271680 at 256, phys: 0x43c40100
b00011000000010011010000000000000, 0x1809a000, 403283968 at 260, phys: 0x43c40104
b00011000010110000000000000000000, 0x18580000, 408420352 at 264, phys: 0x43c40108
b00011000000010110000000000000000, 0x180b0000, 403374080 at 268, phys: 0x43c4010c
b00011000000001001000000000000000, 0x18048000, 402948096 at 272, phys: 0x43c

b01110101111001111110111111010101, 0x75e7efd5, 1978134485 at 4880, phys: 0x43c41310
b01111011110100110111011101001111, 0x7bd3774f, 2077456207 at 4884, phys: 0x43c41314
b11110000111100110110010010100100, 0xf0f364a4, 4042482852 at 4888, phys: 0x43c41318
b10110001011001100001101100001111, 0xb1661b0f, 2976258831 at 4892, phys: 0x43c4131c
b11110110111000110100100011000101, 0xf6e348c5, 4142090437 at 4896, phys: 0x43c41320
b00010010010111011001010000000100, 0x125d9404, 308122628 at 4900, phys: 0x43c41324
b01111000001110001111011100010101, 0x7838f715, 2016999189 at 4904, phys: 0x43c41328
b00000011011000000110101000010100, 0x03606a14, 56650260 at 4908, phys: 0x43c4132c
b10010011101011111110010001000110, 0x93afe446, 2477777990 at 4912, phys: 0x43c41330
b11001110010100100010111011111110, 0xce522efe, 3461492478 at 4916, phys: 0x43c41334
b00100100010011000001011010111000, 0x244c16b8, 608966328 at 4920, phys: 0x43c41338
b10000111010101110101011010011001, 0x87575699, 2270647961 at 4924, phys: 0x43c41

b00011001101010010000011011011110, 0x19a906de, 430507742 at 6220, phys: 0x43c4184c
b10101011010010011000100111100100, 0xab4989e4, 2873723364 at 6224, phys: 0x43c41850
b10000000000011100110001010000001, 0x800e6281, 2148426369 at 6228, phys: 0x43c41854
b10110000011001100011000000000101, 0xb0663005, 2959486981 at 6232, phys: 0x43c41858
b11000010100110001011100010100010, 0xc298b8a2, 3264788642 at 6236, phys: 0x43c4185c
b01111010101000010010011010100110, 0x7aa126a6, 2057381542 at 6240, phys: 0x43c41860
b01011101110011111001101010001110, 0x5dcf9a8e, 1573886606 at 6244, phys: 0x43c41864
b00001101111001010110100010010001, 0x0de56891, 233138321 at 6248, phys: 0x43c41868
b01110001100011011011001011001111, 0x718db2cf, 1905111759 at 6252, phys: 0x43c4186c
b11001110111000101110010001011000, 0xcee2e458, 3470976088 at 6256, phys: 0x43c41870
b10001000101000000101011001001001, 0x88a05649, 2292209225 at 6260, phys: 0x43c41874
b11011000000100010011010000001101, 0xd811340d, 3625006093 at 6264, phys: 0x43c

In [62]:
# Save to file
# (l0_output*2**-28).astype(np.float32).tofile("data/output/conv0.bin")
# l0_act.tofile("data/output/act0.bin")

# for i in range(len(B_out)):
#     j = i + 1
#     B_out[i].tofile("data/output/conv{}.bin".format(j))
#     B_act[i].tofile("data/output/act{}.bin".format(j))

# l15_out.tofile("data/output/conv15.bin")
# (relu_out*2**-16).astype(np.float32).tofile("data/output/act15.bin")
# (l16_output*2**-32).astype(np.float32).tofile("data/output/conv16.bin")

In [72]:
# # # Reference check
# # vhex = np.vectorize(hex)
# ref = np.fromfile("data/ref/{}x{}/conv0.bin".format(size[0], size[1]), dtype=np.float32)
# print("Conv0:")
# print(l0_output.reshape(48,32,64)[:7,:9,0]*2**-28)
# print("ref:")
# print(ref.reshape(48,32,64)[:7,:9,0])
# print((ref - l0_output*2**-28).mean())

# ref = np.fromfile("data/ref/{}x{}/act0.bin".format(size[0], size[1]), dtype=np.uint32)
# print("Act0:")
# print(l0_act[17:19])
# print(ref[17:19])
# print((ref==l0_act).mean())

ref = np.fromfile("data/ref/{}x{}/conv1.bin".format(size[0], size[1]), dtype=np.float32)
print("Conv1:")
out = B_out[0].reshape(48,32,64)
# out.tofile("data/output/conv15.bin".format(size[0], size[1]))
out2 = np.zeros_like(out, dtype=np.int32)
for k in range(0, 64):
    for j in range(0, size[0]):
        for i in range(0, size[1]):
            T = 9*64
            if (i==0 or i==size[1]-1):
                T -= 3*64;
            if (j==0 or j==size[0]-1):
                T -= 3*64;
            if ((j==0 and i==0) or (j==size[0]-1 and i==0) or (j==0 and i==size[1]-1) or (j==size[0]-1 and i==size[1]-1)):
                T += 1*64;
            out2[j,i,k] = 2*out[j,i,k] - T
print(out2[:8,:8,0])
print(ref.astype(np.float32).reshape(48,32,64)[:8,:8,0])
print("{}% OK".format((ref.reshape(48,32,64)==out2).mean() * 100))

# ref = np.fromfile("data/ref/{}x{}/act1.bin".format(size[0], size[1]), dtype=np.uint32)
# print("Act1:")
# print(B_act[0].reshape(48,32,2)[:4,:4,:2])
# print("ref:")
# print(ref.reshape(48,32,2)[:4,:4,:2])
# print((ref==B_act[0]).mean())

# ref = np.fromfile("data/ref/{}x{}/act15.bin".format(size[0], size[1]), dtype=np.float32)
# out = relu_out#*2**-16
# ref = (ref*2**16).round().astype(np.int16)
# print("Act15:")
# print(out.reshape(48,32,64)[0,0,:])
# # print((ref.reshape(48,32,64)[0,0,:]*2**16).round().astype(np.int16))
# print(ref.reshape(48,32,64)[0,0,:])
# print((ref==out).mean())
# print((ref-out).mean())

# ref = np.fromfile("data/ref/{}x{}/conv16.bin".format(size[0], size[1]), dtype=np.float32)
# print("Conv16:")
# out = l16_output*2**-32
# print(out.reshape(48,32)[:6,:8])
# print("ref:")
# print(ref.reshape(48,32)[:6,:8])
# print((ref - out).mean())

Conv1:
[[ 56 108 104  92  76  88  66  56]
 [ 74 152 154 140 136 140 136 106]
 [ 80 170 168 144 134 158 138 114]
 [ 80 170 162 130 128 154 146 134]
 [ 82 168 164 122 130 152 144 150]
 [ 82 170 160 124 134 148 162 170]
 [ 84 168 162 126 142 154 152 158]
 [ 84 162 160 132 150 156 150 170]]
[[  56.  108.  104.   92.   76.   88.   66.   56.]
 [  74.  152.  154.  140.  136.  140.  136.  106.]
 [  80.  170.  168.  144.  134.  158.  138.  114.]
 [  80.  170.  162.  130.  128.  154.  146.  134.]
 [  82.  168.  164.  122.  130.  152.  144.  150.]
 [  82.  170.  160.  124.  134.  148.  162.  170.]
 [  84.  168.  162.  126.  142.  154.  152.  158.]
 [  84.  162.  160.  132.  150.  156.  150.  170.]]
100.0% OK


In [64]:
# !python3 compare.py

In [65]:
# Clear CMA memory
l0_input.close()
l0_weights.close()
l0_output.close()
l0_act.close()

for i in range(len(B_out)):
    B_out[i].close()
    B_w[i].close()
    B_act[i].close()
    B_thres[i].close()

l15_out.close()
relu_thres_a.close()
relu_thres_b.close()
relu_out.close()

l16_weights.close()
l16_output.close()

In [153]:
# ref = np.fromfile("data/ref/{}x{}/act1.bin".format(size[0], size[1]), dtype=np.uint32)
# start = 2
# end = start + 3
# for i in range(start, end):
#     print("b{} ".format(bin(B_act[0][i])[2:].zfill(32)), end='')
# print()
# for i in range(start, end):
#     print("b{} ".format(bin(ref[i])[2:].zfill(32)), end='')

b00000000000000000000000000000000 b00000000000000000000000000000000 b00000000000000000000000000000000 
b11001111111100000010101101100000 b11000010101010100011011010000001 b11001011111100100110101100100000 

In [56]:
# vhex=np.vectorize(hex)